CALLBACK_PATH="Conditional_GANs_mnist.pth.tar"
TENSORBOARD_PATH="Tensorboard"

BATCH_SIZE=64
F_DIM=100
EPOCHS=10
LEARNING_RATE=1e-4

LAMDA_GP=10
NUM_CLASSES=10
IMG_SIZE=64
NUM_EMBEDDING=100
CHANNEL_IMG=1

LOAD_CHECKPOINTS=False
TRAIN=True
TEST=True